apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openai-newsletter-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: newsletter-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openai-newsletter-api
                port:
                  number: 8000
  tls:
  - hosts:
    - newsletter-api.example.com
    secretName: openai-newsletter-api-tls
