# Service to expose FastAPI API on port 8000
---
apiVersion: v1
kind: Service
metadata:
  name: openai-newsletter-api
  labels:
    app: openai-newsletter-api
    component: api
spec:
  type: ClusterIP
  selector:
    app: openai-newsletter-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
